TUNE_TEMP_PATH = "tune.temp.path"
TUNE_PREFIX = "__tune_"
TUNE_DATASET_DF_PREFIX = TUNE_PREFIX + "df__"
TUNE_DATASET_PARAMS_PREFIX = TUNE_PREFIX + "params__"
TUNE_DATASET_TRIALS = TUNE_PREFIX + "trials__"

TUNE_REPORT_METRIC = TUNE_PREFIX + "metric__"
TUNE_REPORT = TUNE_PREFIX + "report__"
